development:
  adapter: postgresql
  encoding: unicode
  database: wedding_development
  pool: 5
  username: amatheny
  password: 
  
test:
  adapter: postgresql
  encoding: unicode
  database: wedding_test
  pool: 5
  username: amatheny
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: wedding
  pool: 5
  username: amatheny
  password: 
