development:
  adapter: mysql2
  database: wedding-dev
  username: root
  password: root

test:
  adapter: mysql2
  database: wedding-test
  username: root
  password: root

production:
  adapter: mysql2
  database: wedding
  username: root
  password: "WBiPEdV"
