development:
  adapter: mysql2
  database: wedding-website-development
  username: root
  password: root

test:
  adapter: mysql2
  database: wedding-website-test
  username: root
  password: root

production:
  adapter: mysql2
  database: matheeen_wedding
  username: matheeen_root
  password: "*WBiP=@-)EdV"
